from splot.splot import data_dict, Splot

# plot axis setup: a plot for multiple meas, cal and diff 
# The diff curves are generated by the splot
myplot = Splot()

r = [0, 20, 50, 80, 100]
for i in r:
    # load the data:
    dataPath = "data/4/"+str(i)
    G = data_dict(dataPath, samplename ='Ag', scan = str(i), 
                  marker = 'o', Linestyle='')

    # plot data: y offset is set to the number of the file name a factor of 1.2
    # Set diff curves be at the same position with the Meas or Calc
    myplot.plot_data(**G, offsety = i*1.2, calc=True, diff = True, diffoffset=0)
    
# Optional: Resize the figure to be taller
myplot.figure_size(6, 8.5)

# Figure configuration: add an outside legend for all data sets 
myplot.config(legend='out')

# Show figure then save
myplot.show()
myplot.save(name = 'Example_4_MultiMeasCalcDiff', form = 'pdf')