from splot.splot import data_dict, Splot, c
import numpy as np

# plot axis setup: a plot for multiple meas, cal and diff 
# The diff curves are generated by the splot
myplot = Splot()

r = [0, 20, 50, 80, 100]
for i in r:
    # load the data:
    dataPath = "data/4/"+str(i)
    r = np.loadtxt(dataPath, skiprows=4, usecols=(0,))
    gtrunc = np.loadtxt(dataPath, skiprows=4, usecols=(1,))
    gcalc = np.loadtxt(dataPath, skiprows=4, usecols=(3,))
    gdiff = np.loadtxt(dataPath, skiprows=4, usecols=(2,))

    #Set up data: G -- Measure data, Gcal -- Calcauted data 
    #             Gdiff -- diff between G and Gcal. In this exmaple we will not
    #                      plot this Gdiff, but use the splot to generat diff
    G = data_dict((r, gtrunc),  samplename = "Ag", scan = str(i),
                  marker = 'o', color = c[i//10+1])
    Gcalc = data_dict((r, gcalc), color = c[5], scan='Calculated')
#    Gdiff = data_dict((r, gdiff),  color = 'g')

    #plot data: y offset is set to the number of the file name a factor of 1.2 
    myplot.plot_data(**G, offsety=i*1.2)

    #plot calculated curve at the same position, add outside legend
    myplot.plot_data(**Gcalc, offsety=i*1.2, diff=True, legend='out')

    #reset the panel at subplot(0,0) for replotting an new data set with the
    # diff curve
    myplot.clear_data(0,0)
    
# Resize the figure to be taller
#myplot.figure_size(4, 8)

# Show figure and save
#myplot.show()
myplot.save(name = 'Example_4_MultiMeasCalcDiff', form = 'pdf')