from splot.splot import data_dict, Splot
import numpy as np

#get the dataPaths:
dataPath1 = "data/1/80"
dataPath2 = "data/1/10"

# Load Data Set 1:
r1 = np.loadtxt(dataPath1, skiprows=4, usecols=(0,))
Gtrunc1 = np.loadtxt(dataPath1, skiprows=4, usecols=(1,))
Gdiff1 = np.loadtxt(dataPath1, skiprows=4, usecols=(2,))
Gcalc1 = np.loadtxt(dataPath1, skiprows=4, usecols=(3,))

# Load Data Set 2:
r2 = np.loadtxt(dataPath2, skiprows=4, usecols=(0,))
Gtrunc2 = np.loadtxt(dataPath2, skiprows=4, usecols=(1,))
Gdiff2 = np.loadtxt(dataPath2, skiprows=4, usecols=(2,))
Gcalc2 = np.loadtxt(dataPath2, skiprows=4, usecols=(3,))

# Setup Data for the plot: User can set plotting style
g1 = data_dict( (r1, Gtrunc1), samplename ='G1', scan = 'Measured', \
                     marker = 'o')
g1calc = data_dict( (r1, Gcalc1), samplename  = 'G1', scan = 'Calc', \
                    color = 'C5')
g1diff = data_dict( (r1, Gdiff1), samplename = 'G1', scan = 'Diff', \
                    color = 'g')

# Setup Data for the plot: 
g2 = data_dict( (r2, Gtrunc2), samplename ='G2', scan = 'Measured', \
                     marker = 'o', color = 'C2')
g2calc = data_dict( (r2, Gcalc2), samplename = 'G2', scan = 'Calc', color ='C5')
g2diff = data_dict( (r2, Gdiff2), samplename = 'G2', scan = 'Diff')

# plot axis setup: 2 rows x 1 col
myplot = Splot(2, 1)

# plot data set 1 at upper left panel, plot diff curve from the data set
myplot.plot_data(**g1, r=0, c=0)
myplot.plot_data(**g1calc, r=0, c=0)
# plot the diff curve and manually set its offset to be -4
myplot.plot_data(**g1diff, r=0, c=0, offsety = -4) 

## plot data set 2 at lower left panel, the diff curve is generated by splot
myplot.plot_data(**g2, r=1, c=0)
myplot.plot_data(**g2calc, r=1, c=0, diff = True, legend='in')

# See the figure / Save the figure
myplot.show()
myplot.save(name = 'Example_1_TwoPanMeasCalcDiff', form ='pdf')